In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import pickle

WARNING:tensorflow:From c:\Users\Siddharth Verma\Documents\COURSE\python\PROJECTS\ChurnModelling\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [3]:
model=load_model('model.h5')
with open('label_encoder.pkl','rb')as file:
    label_encoder=pickle.load(file)
with open('ohe.pkl','rb')as file:
    ohe=pickle.load(file)
with open('scaler.pkl','rb')as file:
    scaler=pickle.load(file)

WARNING:tensorflow:From c:\Users\Siddharth Verma\Documents\COURSE\python\PROJECTS\ChurnModelling\venv\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [4]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [5]:
geo_encoded=ohe.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=ohe.get_feature_names_out(['Geography']))
geo_encoded_df
input_df=pd.DataFrame([input_data])

c:\Users\Siddharth Verma\Documents\COURSE\python\PROJECTS\ChurnModelling\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [6]:
input_df=pd.concat([input_df.reset_index(drop=True),geo_encoded_df],axis=1)
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [7]:
input_df['Gender']=label_encoder.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [ ]:
input_df=input_df.drop("Geography",axis=1)

KeyError: "['Geography'] not found in axis"

In [10]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [12]:
scaled_data=scaler.transform(input_df)
prediction=model.predict(scaled_data)
prediction

1/1 [==============================] - 0s 104ms/step

array([[0.02692049]], dtype=float32)

In [15]:
prediction_prob=prediction[0][0]
prediction_prob
if(prediction_prob>0.5):
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.